workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  npm-build:
    group: prepare
    image: node:9.5.0
    commands:
      - npm install --unsafe-perm
      - npm run build

  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      # Perform a composer install to work around an issue where an update
      # without a lock file present affects the resolving of dependencies.
      # Todo: Remove the `composer install` when the composer bug is fixed.
      # Ref. https://github.com/composer/composer/issues/7542
      # Ref. https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer install --ansi --no-suggest --no-progress
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      # Reset permission since installation runs as root. @todo Fix this.
      - ./vendor/bin/drush -y config-set system.performance css.preprocess 0
      - ./vendor/bin/drush -y config-set system.performance js.preprocess 0
      - ./vendor/bin/behat --strict

  before-release:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run release:create-archive --tag=${DRONE_TAG}
    when:
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      event: tag
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
